### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by missinglink** [mapzen/opzworks#15]
```
$ opzworks
/home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/lib/opzworks/commands/berks.rb:162: syntax error, unexpected ':', expecting => (SyntaxError)
                delete_arr.each { |i| arr_of_hash << { 'key': i } }
                                                             ^
	from /home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/lib/opzworks.rb:8:in `block in <top (required)>'
	from /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/lib/opzworks.rb:7:in `each'
	from /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/lib/opzworks.rb:7:in `<top (required)>'
	from /home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/lib/opzworks/cli.rb:4:in `<top (required)>'
	from /home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/peter/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/peter/.rvm/gems/ruby-2.1.2/gems/opzworks-0.12.4/bin/opzworks:8:in `<top (required)>'
	from /home/peter/.rvm/gems/ruby-2.1.2/bin/opzworks:23:in `load'
	from /home/peter/.rvm/gems/ruby-2.1.2/bin/opzworks:23:in `<main>'
	from /home/peter/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/peter/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by heffergm** [comment]
Upgrade to ruby 2.3.

**Comment by missinglink** [comment]
thanks, upgrading to `2.3` resolved the issue.
